### ISSUE TITLE
Change readme to match latest understanding

### ISSUE THREAD

**Issue by eggsyntax** [yogthos/clojure-error-message-catalog#16]
The [error page submitted on 04/29](https://github.com/yogthos/clojure-error-message-catalog/blob/master/clj/java-lang-boolean-cannot-be-cast-to-clojure-lang-symbol.md) uses a somewhat different format than is recommended on the readme. It was done using this format based on [conversation in slack](http://clojurians-log.mantike.pro/error-message-catalog/2016-04-30.html) about whether error pages should ultimately reflect a single exception, or a single cause of a single exception. The decision made on the fly was that one page equals one error. To fit that, the referenced page uses the following Markdown format for sections:

```
## <Text of the exception message>
### General description of exception
### Cause 1
### Solution 1
### Cause 2
### Solution 2
```

I propose that the readme be changed to reflect that (and I'd be happy to take that on), but wanted to get buy-in from other folks on the project first. This may not be the final decision on format, but I think it makes sense to have the readme reflect our most current understanding.

Note that this change is consistent with [issue 14](https://github.com/yogthos/clojure-error-message-catalog/issues/14), but potentially conflicts with some of the formats proposed in  [issue 6](https://github.com/yogthos/clojure-error-message-catalog/issues/6).

**Comment by lacarmen** [comment]
You did this change in #19 right?

**Comment by eggsyntax** [comment]
I did, forgot to close the ticket. Thanks!
