### ISSUE TITLE
IllegalArgumentException Don't know how to create ISeq from: example.core$eval34632$fn__34633  clojure.lang.RT.seqFrom (RT.java:548)

### ISSUE THREAD

**Issue by tosh** [yogthos/clojure-error-message-catalog#29]
(sorry for posting this as issue instead of a pull request)

While I was half asleep I was using a threading macro (`->`) to filter some elements:

```Clojure
(-> [1, 2, 3, 4, 5]
  (filter odd?))
```

and got confused by the exception this caused. Later I realized I should have used `->>` instead.

**Comment by yogthos** [comment]
thanks, I added the following doc https://github.com/yogthos/clojure-error-message-catalog/blob/master/clj/dont-know-how-to-create-ISeq.md
