### ISSUE TITLE
Wrong parentheses kind when creating keyword'ed map

### ISSUE THREAD

**Issue by socksy** [yogthos/clojure-error-message-catalog#8]
Found this with a teaching session with a Clojure beginner:

    IllegalArgumentException Wrong number of args passed to keyword: :bread

Clearly this only works when the first item in the list is a keyword (in this case :bread).

**Comment by yogthos** [comment]
I guess there are two possible gotchas here, one if you have a map with a single key where you just get a `nil` such as `(:foo "baguette")`, and the error with multiple keys.

**Comment by yogthos** [comment]
How does [this](https://github.com/yogthos/clojure-error-message-catalog/blob/master/clj/wrong-parens-used-to-create-a-map.md) look?

**Comment by socksy** [comment]
Of course, the reason why keywords can take arguments at all :)
For me your write up looks great!

**Comment by yogthos** [comment]
Once nice thing about keywords behaving like functions is that you can avoid nil checks that way, but it would've been better if keywords threw an error when passed invalid arguments I think.
